protect multi set add data, use default bd anf fs for tests
davidsaada/mbed-os pull request #16
Opened 2018-11-01 15:05 UTC by offirko

KVStore Integration tests branch
    [X] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

2018-11-01 15:21 UTC, offirko commented
@theamirocohen , @dannybenor , @davidsaada , @yossi2le - New PR with set_add_data updates and FileSystemStore Test uses default BD and FS

2018-11-01 16:25 UTC, dannybenor requested changes

2018-11-01 16:25 UTC, dannybenor commented on features/storage/TESTS/kvstore/filesystemstore/fsst_tests/main.cpp
> +BlockDevice *bd = BlockDevice::get_default_instance();
You need to be prepared for targets where there are no components, therefore you will not get a bd from get_default_instance();

2018-11-04 05:55 UTC, offirko commented on features/storage/TESTS/kvstore/filesystemstore/fsst_tests/main.cpp
> +BlockDevice *bd = BlockDevice::get_default_instance();
Thanks, I'll skip the test if it returns NULL

2018-11-04 05:58 UTC, offirko commented on features/storage/TESTS/kvstore/filesystemstore/fsst_tests/main.cpp
> +BlockDevice *bd = BlockDevice::get_default_instance();
@dannybenor - is there an additional option to define a BlockDevice with a FS and test such a target ?

2018-11-05 16:50 UTC, closed without merging