Offir fsstore2
davidsaada/mbed-os pull request #17
Opened 2018-11-05 16:53 UTC by offirko

### Description
Delivering FileSystemStore to KVStore Integration

### Pull request type
    [ ] Fix
    [ ] Refactor
    [ ] Target update
    [X] Functionality change
    [ ] Docs update
    [ ] Test update
    [ ] Breaking change

2018-11-05 16:54 UTC, offirko commented
@theamirocohen @davidsaada @dannybenor @yossi2le - FileSystemStore PR into KVStore Integration

2018-11-05 17:27 UTC, davidsaada requested changes

2018-11-05 17:27 UTC, davidsaada commented on features/storage/kvstore/filesystemstore/FileSystemStore.h
> +    virtual int get(const char *key, void *buffer, size_t buffer_size, size_t *actual_size, size_t offset = 0);
The `actual_size` parameter should also be optional (if 0, you shouldn't return the value).

2018-11-05 17:27 UTC, davidsaada commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +    if ((!is_valid_key(key)) || (size > KVStore::MAX_KEY_SIZE) || ((buffer == NULL) && (size > 0)) ) {
The size check here is wrong - you're checking the data size against the key size. This check should be removed (we don't have a limit for the data size).

2018-11-05 17:27 UTC, davidsaada commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +        status = MBED_ERROR_INVALID_SIZE;
Should return invalid argument here.

2018-11-05 17:27 UTC, davidsaada commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +
Should check key validity here.

2018-11-05 17:27 UTC, davidsaada commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +    if ((!is_valid_key(key)) || (handle == NULL) ) {
Doesn't `verify_key_file` already perform the key validation?

2018-11-05 17:27 UTC, davidsaada commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +    if (key == NULL) {
Isn't this checked by `verify_key_file`?

2018-11-06 07:53 UTC, offirko commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +    if ((!is_valid_key(key)) || (size > KVStore::MAX_KEY_SIZE) || ((buffer == NULL) && (size > 0)) ) {
oops, will fix

2018-11-06 07:53 UTC, offirko commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +
key validity is checked within _verify_key_file(), common to get(), get_info() and remove()

2018-11-06 07:53 UTC, offirko commented on features/storage/kvstore/filesystemstore/FileSystemStore.cpp
> +    if (key == NULL) {
you're right , now that I've added is_valid_key() its no longer needed - I'll remove.
Same below for set_start.

2018-11-06 07:53 UTC, offirko commented on features/storage/kvstore/filesystemstore/FileSystemStore.h
> +    virtual int get(const char *key, void *buffer, size_t buffer_size, size_t *actual_size, size_t offset = 0);
Thanks.The code itself is implemented like you said. I'll fix the prototype.

2018-11-06 08:25 UTC, offirko commented
@davidsaada - pushed updated version with fixes related to your CR

2018-11-07 14:51 UTC, closed without merging